name: "Git commit"

description: "Git commit"

inputs:
  message:
    description: "Commit messsage"
    required: true
  repo_dir:
    description: "Directory to add & commit"
    required: true
  auto_resolve_conflicts:
    description: "Use '-X ours' on rebase"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup GIT
      uses: raycast/github-actions/setup-git@v1.12.0
    - name: Commit
      shell: bash
      working-directory: ${{ inputs.repo_dir }}
      run: |
        if ! [[ -z $(git status -s .) ]] ; then
          git add .
          git status .
          git commit --message "${{ inputs.message }}"

          branch_name=$(git rev-parse --abbrev-ref HEAD)
          git_conflicts="" && [[ "${{ inputs.auto_resolve_conflicts }}" == true ]] && git_conflicts="-X ours"
          git fetch origin $branch_name
          git rebase origin/$branch_name $git_conflicts
          git push -u origin $branch_name
        else
          echo "No changes, skipping sync."
        fi
