name: "Git Post Store URLs to PR"

description: "Git Post Store URLs to PR"

inputs:
  store_urls:
    description: "Store URLs to published extensions"
    required: true
  github_token:
    description: "Github Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup GIT
      uses: raycast/github-actions/setup-git@v1.17.0
    - name: Extract platforms from package.json
      id: extract_platforms  
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          platforms=$(jq -r '.platforms // ["macos"] | map(if . == "macos" then "macOS" elif . == "windows" then "Windows" else . end) | join(", ")' package.json 2>/dev/null || echo "macOS")
        else
          platforms="macOS"
        fi
        echo "platforms=$platforms" >> $GITHUB_OUTPUT
    - name: Check message
      id: check_message
      shell: bash
      run: |
        if [ ! -z "${{ inputs.store_urls }}" ]; then
          echo "message_exists=true" >> $GITHUB_OUTPUT
        fi
    - uses: mshick/add-pr-comment@v2
      if: ${{ steps.check_message.outputs.message_exists }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        message: |
          **Published to the Raycast Store:** (${{ steps.extract_platforms.outputs.platforms }})
          ${{ inputs.store_urls }}
        allow-repeats: true
