name: "Extensions build & publish"

description: "Extensions build & publish"

inputs:
  access_token:
    description: "Raycast Access Token"
    required: false
  command:
    description: "Ray CLI command (build | publish)"
    required: false
  paths:
    description: "Paths to execute on"
    required: false
  cli_version:
    description: "CLI Version"
    required: false
  npm_token:
    description: "NPM token"
    required: false
  extension_schema:
    description: "Extension schema"
    required: false
  allow_owners_only_for_extensions:
    description: "Whitelist extensions allowed to have owners - each extension in new line. If not set or empty, all extensions are allowe to have it."
    required: false
outputs:
  command:
    description: "Ray CLI command executed"
    value: ${{ steps.get_command.outputs.command }}
  paths:
    description: "Paths for changed extensions"
    value: ${{ steps.get_changed_extensions.outputs.paths }}
  store_urls:
    description: "Store URLs for published extensions"
    value: ${{ steps.ray_cli.outputs.store_urls }}
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.1
    - name: Setup CLI
      uses: raycast/github-actions/setup-cli@f/update-setup-cli
      with:
        version: ${{ inputs.cli_version || '1.86.0-alpha.91' }}
        npm_token: ${{ inputs.npm_token }}
    - name: Get command
      id: get_command
      uses: raycast/github-actions/get-command@v1.16.0
      with:
        custom_command: ${{ inputs.command }}
        github_event_name: ${{ github.event_name }}
    - name: Get changed extensions
      id: get_changed_extensions
      uses: raycast/github-actions/get-changed-extensions@v1.16.0
      with:
        custom_paths: ${{ inputs.paths }}
        github_event_name: ${{ github.event_name }}
    - name: Ray CLI
      id: ray_cli
      uses: raycast/github-actions/ray-cli@f/update-setup-cli
      with:
        paths: ${{ steps.get_changed_extensions.outputs.paths }}
        command: ${{ steps.get_command.outputs.command }}
        access_token: ${{ inputs.access_token }}
        npm_token: ${{ inputs.npm_token }}
        extension_schema: ${{ inputs.extension_schema }}
        allow_owners_only_for_extensions: ${{ inputs.allow_owners_only_for_extensions }}
