name: "Setup Raycast CLI"

description: "Setup Raycast CLI"

inputs:
  version:
    description: "CLI version (format: 1.0.0)"
    required: true
  npm_token:
    description: "NPM token"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      shell: bash
      run: |
        ${{ github.action_path }}/setup_cli.sh "${{ inputs.version }}" "${{ inputs.npm_token }}"
