name: "Setup Raycast CLI"

description: "Setup Raycast CLI"

inputs:
  version:
    description: "CLI version (format: 1.0.0)"
    required: true
  raycast_api_alpha_npm_token:
    description: "NPM token for alpha version of @raycast/api"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_RAYCAST_API_ALPHA_NPM_TOKEN: ${{ inputs.raycast_api_alpha_npm_token }}
      run: |
        "$ACTION_PATH/setup_cli.sh" "$INPUT_VERSION" "$INPUT_RAYCAST_API_ALPHA_NPM_TOKEN"
