name: "Setup 1Password CLI"
description: "Setup 1Password CLI"

runs:
  using: "composite"
  steps:
    - name: Install 1Password CLI on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if (Get-Command op -ErrorAction SilentlyContinue) {
          Write-Host "1Password CLI is already installed"
          exit 0
        }
        Invoke-WebRequest "https://app-updates.agilebits.com/check/1/0/CLI2/en/2.0.0/N" -OutFile op.json
        $opVersion = Get-Content -Raw -Path op.json | ConvertFrom-Json | select -ExpandProperty version
        $installDir = Join-Path -Path $pwd -ChildPath 'op'
        Invoke-WebRequest -Uri "https://cache.agilebits.com/dist/1P/op2/pkg/v$($opVersion)/op_windows_amd64_v$($opVersion).zip" -OutFile op.zip
        Expand-Archive -Path op.zip -DestinationPath $installDir -Force
        "$installDir" | Out-File -FilePath $env:GITHUB_PATH -Append
    - name: Install 1Password CLI on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -o pipefail
        if command -v op &> /dev/null; then
          echo "1Password CLI is already installed"
          exit 0
        fi
        brew install 1password-cli 2>&1 | grep -v "disabled for this Cask"
    - name: Install 1Password CLI on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -o pipefail
        if command -v op &> /dev/null; then
          echo "1Password CLI is already installed"
          exit 0
        fi
        ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/;s/armv7l/arm/')
        OP_VERSION=$(curl -s https://app-updates.agilebits.com/check/1/0/CLI2/en/2.0.0/N | grep -o '"version":"[^"]*' | cut -d'"' -f4)
        wget "https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_VERSION}/op_linux_${ARCH}_v${OP_VERSION}.zip" -O op.zip
        unzip -d op op.zip
        sudo mv op/op /usr/local/bin/
        rm -r op.zip op
        sudo groupadd -f onepassword-cli
        sudo chgrp onepassword-cli /usr/local/bin/op
        sudo chmod g+s /usr/local/bin/op
