name: "Raycast CLI"

description: "Raycast CLI"

inputs:
  paths:
    description: "Paths to execute on"
    required: true
  command:
    description: "Ray CLI command (build | publish)"
    required: true
  access_token:
    description: "Raycast Access Token"
    required: false
  extension_schema:
    description: "Extension schema"
    required: false
  allow_owners_only_for_extensions:
    description: "Whitelist extensions allowed to have owners - each extension in new line. If not set or empty, all extensions are allowe to have it."
    required: false
  npmrc_path:
    description: "Path to npmrc file to access private npm packages"
    required: false
  raycast_api_alpha_npm_token:
    description: "NPM token for alpha version of @raycast/api"
    required: false
outputs:
  store_urls:
    description: "Store URLs for published extensions"
    value: ${{ steps.ray_cli.outputs.store_urls }}
runs:
  using: "composite"
  steps:
    - name: Execute command
      shell: bash
      id: ray_cli
      env:
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      run: |
        set -e -o noglob
        ${{ github.action_path }}/ray_cli.sh "${{ inputs.command }}" "${{ inputs.paths }}" "${{ inputs.access_token }}" "${{ inputs.extension_schema }}" "${{ inputs.allow_owners_only_for_extensions }}" "${{ inputs.npmrc_path }}" "${{ inputs.raycast_api_alpha_npm_token }}"
